import Jabatan from '#models/jabatan'
import Penugasan from '#models/penugasan'
import User from '#models/user'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    // Write your database queries inside the run method
    console.log("Mulai Membuat Data User")

    //User 
    const user = await User.createMany([
      { username: 'admin', nama: 'Admin', email: 'admin@admin.com' },
      { username: 'user1', nama: 'User 1', email: 'user1@user.com' },
      { username: 'user2', nama: 'User 2', email: 'user2@user.com' },
      { username: 'user3', nama: 'User 3', email: 'user3@user.com' },
      { username: 'user4', nama: 'User 4', email: 'user4@user.com' },
      { username: 'user5', nama: 'User 5', email: 'user5@user.com' },
      { username: 'user6', nama: 'User 6', email: 'user6@user.com' },
      { username: 'user7', nama: 'User 7', email: 'user7@user.com' },
      { username: 'user8', nama: 'User 8', email: 'user8@user.com' },
      { username: 'user9', nama: 'User 9', email: 'user9@user.com' },
      { username: 'user10', nama: 'User 10', email: 'user10@user.com' },
      { username: 'user11', nama: 'User 11', email: 'user11@user.com' },
      { username: 'user12', nama: 'User 12', email: 'user12@user.com' },
      { username: 'user13', nama: 'User 13', email: 'user13@user.com' },
      { username: 'user14', nama: 'User 14', email: 'user14@user.com' },
      { username: 'user15', nama: 'User 15', email: 'user15@user.com' },
      { username: 'user16', nama: 'User 16', email: 'user16@user.com' },
      { username: 'user17', nama: 'User 17', email: 'user17@user.com' },
      { username: 'user18', nama: 'User 18', email: 'user18@user.com' },
      { username: 'user19', nama: 'User 19', email: 'user19@user.com' },
      { username: 'user20', nama: 'User 20', email: 'user20@user.com' },
      { username: 'user21', nama: 'User 21', email: 'user21@user.com' },
      { username: 'user22', nama: 'User 22', email: 'user22@user.com' },
      { username: 'user23', nama: 'User 23', email: 'user23@user.com' },
      { username: 'user24', nama: 'User 24', email: 'user24@user.com' },
      { username: 'user25', nama: 'User 25', email: 'user25@user.com' },
      { username: 'user26', nama: 'User 26', email: 'user26@user.com' },
      { username: 'user27', nama: 'User 27', email: 'user27@user.com' },
      { username: 'user28', nama: 'User 28', email: 'user28@user.com' },
      { username: 'user29', nama: 'User 29', email: 'user29@user.com' },
      { username: 'user30', nama: 'User 30', email: 'user30@user.com' },
      { username: 'user31', nama: 'User 31', email: 'user31@user.com' },
      { username: 'user32', nama: 'User 32', email: 'user32@user.com' },
      { username: 'user33', nama: 'User 33', email: 'user33@user.com' },
      { username: 'user34', nama: 'User 34', email: 'user34@user.com' },
      { username: 'user35', nama: 'User 35', email: 'user35@user.com' },
      { username: 'user36', nama: 'User 36', email: 'user36@user.com' },
      { username: 'user37', nama: 'User 37', email: 'user37@user.com' },
      { username: 'user38', nama: 'User 38', email: 'user38@user.com' },
      { username: 'user39', nama: 'User 39', email: 'user39@user.com' },
      { username: 'user40', nama: 'User 40', email: 'user40@user.com' },
      { username: 'user41', nama: 'User 41', email: 'user41@user.com' },
      { username: 'user42', nama: 'User 42', email: 'user42@user.com' },
      { username: 'user43', nama: 'User 43', email: 'user43@user.com' },
      { username: 'user44', nama: 'User 44', email: 'user44@user.com' },
      { username: 'user45', nama: 'User 45', email: 'user45@user.com' },
      { username: 'user46', nama: 'User 46', email: 'user46@user.com' },
      { username: 'user47', nama: 'User 47', email: 'user47@user.com' },
      { username: 'user48', nama: 'User 48', email: 'user48@user.com' },
      { username: 'user49', nama: 'User 49', email: 'user49@user.com' },
      { username: 'user50', nama: 'User 50', email: 'user50@user.com' },
      { username: 'user51', nama: 'User 51', email: 'user51@user.com' },
      { username: 'user52', nama: 'User 52', email: 'user52@user.com' },
      { username: 'user53', nama: 'User 53', email: 'user53@user.com' },
      { username: 'user54', nama: 'User 54', email: 'user54@user.com' },
      { username: 'user55', nama: 'User 55', email: 'user55@user.com' },
      { username: 'user56', nama: 'User 56', email: 'user56@user.com' },
      { username: 'user57', nama: 'User 57', email: 'user57@user.com' },
      { username: 'user58', nama: 'User 58', email: 'user58@user.com' },
      { username: 'user59', nama: 'User 59', email: 'user59@user.com' },
      { username: 'user60', nama: 'User 60', email: 'user60@user.com' },
      { username: 'user61', nama: 'User 61', email: 'user61@user.com' },
      { username: 'user62', nama: 'User 62', email: 'user62@user.com' },
      { username: 'user63', nama: 'User 63', email: 'user63@user.com' },
      { username: 'user64', nama: 'User 64', email: 'user64@user.com' },
      { username: 'user65', nama: 'User 65', email: 'user65@user.com' },
      { username: 'user66', nama: 'User 66', email: 'user66@user.com' },
      { username: 'user67', nama: 'User 67', email: 'user67@user.com' },
      { username: 'user68', nama: 'User 68', email: 'user68@user.com' },
      { username: 'user69', nama: 'User 69', email: 'user69@user.com' },
      { username: 'user70', nama: 'User 70', email: 'user70@user.com' },
      { username: 'user71', nama: 'User 71', email: 'user71@user.com' },
      { username: 'user72', nama: 'User 72', email: 'user72@user.com' },
      { username: 'user73', nama: 'User 73', email: 'user73@user.com' },
      { username: 'user74', nama: 'User 74', email: 'user74@user.com' },
      { username: 'user75', nama: 'User 75', email: 'user75@user.com' },
      { username: 'user76', nama: 'User 76', email: 'user76@user.com' },
      { username: 'user77', nama: 'User 77', email: 'user77@user.com' },
      { username: 'user78', nama: 'User 78', email: 'user78@user.com' },
      { username: 'user79', nama: 'User 79', email: 'user79@user.com' },
      { username: 'user80', nama: 'User 80', email: 'user80@user.com' },
      { username: 'user81', nama: 'User 81', email: 'user81@user.com' },
      { username: 'user82', nama: 'User 82', email: 'user82@user.com' },
      { username: 'user83', nama: 'User 83', email: 'user83@user.com' },
      { username: 'user84', nama: 'User 84', email: 'user84@user.com' },
      { username: 'user85', nama: 'User 85', email: 'user85@user.com' },
      { username: 'user86', nama: 'User 86', email: 'user86@user.com' },
      { username: 'user87', nama: 'User 87', email: 'user87@user.com' },
      { username: 'user88', nama: 'User 88', email: 'user88@user.com' },
      { username: 'user89', nama: 'User 89', email: 'user89@user.com' },
      { username: 'user90', nama: 'User 90', email: 'user90@user.com' },
      { username: 'user91', nama: 'User 91', email: 'user91@user.com' },
      { username: 'user92', nama: 'User 92', email: 'user92@user.com' },
      { username: 'user93', nama: 'User 93', email: 'user93@user.com' },
      { username: 'user94', nama: 'User 94', email: 'user94@user.com' },
      { username: 'user95', nama: 'User 95', email: 'user95@user.com' },
      { username: 'user96', nama: 'User 96', email: 'user96@user.com' },
      { username: 'user97', nama: 'User 97', email: 'user97@user.com' },
      { username: 'user98', nama: 'User 98', email: 'user98@user.com' },
      { username: 'user99', nama: 'User 99', email: 'user99@user.com' },
      { username: 'user100', nama: 'User 100', email: 'user100@user.com' },
      { username: 'user101', nama: 'User 101', email: 'user101@user.com' },
      { username: 'user102', nama: 'User 102', email: 'user102@user.com' },
      { username: 'user103', nama: 'User 103', email: 'user103@user.com' },
      { username: 'user104', nama: 'User 104', email: 'user104@user.com' },
      { username: 'user105', nama: 'User 105', email: 'user105@user.com' },
      { username: 'user106', nama: 'User 106', email: 'user106@user.com' },
      { username: 'user107', nama: 'User 107', email: 'user107@user.com' },
      { username: 'user108', nama: 'User 108', email: 'user108@user.com' },
      { username: 'user109', nama: 'User 109', email: 'user109@user.com' },
      { username: 'user110', nama: 'User 110', email: 'user110@user.com' },
      { username: 'user111', nama: 'User 111', email: 'user111@user.com' },
      { username: 'user112', nama: 'User 112', email: 'user112@user.com' },
      { username: 'user113', nama: 'User 113', email: 'user113@user.com' },
      { username: 'user114', nama: 'User 114', email: 'user114@user.com' },
      { username: 'user115', nama: 'User 115', email: 'user115@user.com' },
      { username: 'user116', nama: 'User 116', email: 'user116@user.com' },
      { username: 'user117', nama: 'User 117', email: 'user117@user.com' },
      { username: 'user118', nama: 'User 118', email: 'user118@user.com' },
      { username: 'user119', nama: 'User 119', email: 'user119@user.com' },
      { username: 'user120', nama: 'User 120', email: 'user120@user.com' },
      { username: 'user121', nama: 'User 121', email: 'user121@user.com' },
      { username: 'user122', nama: 'User 122', email: 'user122@user.com' },
      { username: 'user123', nama: 'User 123', email: 'user123@user.com' },
      { username: 'user124', nama: 'User 124', email: 'user124@user.com' },
      { username: 'user125', nama: 'User 125', email: 'user125@user.com' },
      { username: 'user126', nama: 'User 126', email: 'user126@user.com' },
      { username: 'user127', nama: 'User 127', email: 'user127@user.com' },
      { username: 'user128', nama: 'User 128', email: 'user128@user.com' },
      { username: 'user129', nama: 'User 129', email: 'user129@user.com' },
      { username: 'user130', nama: 'User 130', email: 'user130@user.com' },
      { username: 'user131', nama: 'User 131', email: 'user131@user.com' },
      { username: 'user132', nama: 'User 132', email: 'user132@user.com' },
      { username: 'user133', nama: 'User 133', email: 'user133@user.com' },
      { username: 'user134', nama: 'User 134', email: 'user134@user.com' },
      { username: 'user135', nama: 'User 135', email: 'user135@user.com' },
      { username: 'user136', nama: 'User 136', email: 'user136@user.com' },
      { username: 'user137', nama: 'User 137', email: 'user137@user.com' },
      { username: 'user138', nama: 'User 138', email: 'user138@user.com' },
      { username: 'user139', nama: 'User 139', email: 'user139@user.com' },
      { username: 'user140', nama: 'User 140', email: 'user140@user.com' },
      { username: 'user141', nama: 'User 141', email: 'user141@user.com' },
      { username: 'user142', nama: 'User 142', email: 'user142@user.com' },
      { username: 'user143', nama: 'User 143', email: 'user143@user.com' },
      { username: 'user144', nama: 'User 144', email: 'user144@user.com' },
      { username: 'user145', nama: 'User 145', email: 'user145@user.com' },
      { username: 'user146', nama: 'User 146', email: 'user146@user.com' },
      { username: 'user147', nama: 'User 147', email: 'user147@user.com' },
      { username: 'user148', nama: 'User 148', email: 'user148@user.com' },
      { username: 'user149', nama: 'User 149', email: 'user149@user.com' },
      { username: 'user150', nama: 'User 150', email: 'user150@user.com' },
    ])

    console.log("Selesai Membuat Data User")

    //Penugasan
    console.log("Mulai Membuat Data Penugasan")
    const jabatan = await Jabatan.all()
    const penugasan = jabatan.map((item, index) => {
      return {
        jabatan: item.id,
        pejabat: user[index].username
      }
    })
    await Penugasan.createMany(penugasan)

    console.log("Selesai Membuat Data")
  }
}